### ISSUE TITLE
Email Not Send.

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/Cofoundry.Plugins.Mail.MailKit#2] opened 2021-04-20 06:45 UTC
I have try to create a new user from admin side it's create successfully but I have face a Issue email not send after create a user.
I have install Plugin send grid .Please help me

**Comment by HeyJoel** [comment] 2021-04-20 16:19
Duplicate of Cofoundry [issue 449](https://github.com/cofoundry-cms/cofoundry/issues/429) and this isn't the SendGrid repo.

**Closed as completed by HeyJoel** 2021-04-20 16:19 UTC
